version: '3.0'
services:
  postgres:
    image: postgres:latest
    container_name: postgresDB
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ytchimp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ytchimp
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ytchimp_server
    env_file:
      - .env.development
    depends_on:
      - postgres
    ports:
      - 3001:3001
    networks:
      - ytchimp
networks:
  ytchimp:
    name: ytchimp
volumes:
  postgres-data: